# Generated by Django 4.2.9 on 2024-06-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='companyname',
            field=models.CharField(default='test', max_length=40),
            preserve_default=False,
        ),
    ]
