# Generated by Django 4.2.9 on 2024-06-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_comments_companyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
