# Generated by Django 4.2.9 on 2024-06-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_comments_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='fsc',
        ),
        migrations.AddField(
            model_name='company',
            name='products',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='survey_answers',
            name='supports_noanimaltesting',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Indifferent', 'Indifferent'), ('No', 'No')], default='Yes', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey_answers',
            name='supports_fairtrade',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Indifferent', 'Indifferent'), ('No', 'No')], max_length=12),
        ),
        migrations.AlterField(
            model_name='survey_answers',
            name='supports_israel',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Indifferent', 'Indifferent'), ('No', 'No')], max_length=12),
        ),
        migrations.AlterField(
            model_name='survey_answers',
            name='supports_lowcarbonemissions',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Indifferent', 'Indifferent'), ('No', 'No')], max_length=12),
        ),
        migrations.AlterField(
            model_name='survey_answers',
            name='supports_nochildlabor',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Indifferent', 'Indifferent'), ('No', 'No')], max_length=12),
        ),
        migrations.AlterField(
            model_name='survey_answers',
            name='supports_palestine',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Indifferent', 'Indifferent'), ('No', 'No')], max_length=12),
        ),
    ]
