# Generated by Django 4.2.9 on 2024-06-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_company_fsc_company_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='supports_israel',
        ),
        migrations.RemoveField(
            model_name='company',
            name='supports_palestine',
        ),
        migrations.RemoveField(
            model_name='survey_answers',
            name='supports_israel',
        ),
        migrations.RemoveField(
            model_name='survey_answers',
            name='supports_palestine',
        ),
        migrations.AlterField(
            model_name='survey_answers',
            name='supports_fairtrade',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='survey_answers',
            name='supports_lowcarbonemissions',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='survey_answers',
            name='supports_noanimaltesting',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='survey_answers',
            name='supports_nochildlabor',
            field=models.BooleanField(),
        ),
    ]
